version: "3.9"

services:
  swapi-app:
    build: .
    container_name: swapiapp
    depends_on:
      - db
    #healthcheck:
    #  test: curl --fail http://127.0.0.1:8080/hello/Marcos || exit 1
    #  interval: 10s
    #  retries: 5
    #  start_period: 5s
    #  timeout: 10s
    environment:
      DB_NAME: 'swapiapp'
      DB_USER: 'swapiapp-user'
      DB_PASSWORD: 'swapiapp-password'
    expose:
      - '8080'
    ports:
      - "8080:8080"

  db:
    image: mysql:8.0
    container_name: db
    restart: always
    environment:
      MYSQL_DATABASE: 'swapiapp'
      MYSQL_USER: 'swapiapp-user'
      MYSQL_PASSWORD: 'swapiapp-password'
      MYSQL_ROOT_PASSWORD: 'mysql_root_password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - swapiapp-volume:/var/lib/mysql
volumes:
  swapiapp-volume: